# Generated by Django 6.0.2 on 2026-06-06 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_ranksnapshot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ranksnapshot',
            new_name='accounts_ra_user_id_3f32ea_idx',
            old_name='accounts_ra_user_id_taken_at_idx',
        ),
    ]
