server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    resolver 8.8.8.8 valid=30s;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        set $backend "https://predict-mate-backend.fly.dev";
        proxy_pass $backend;
        proxy_set_header Host predict-mate-backend.fly.dev;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_ssl_server_name on;
    }

    location /media/ {
        set $backend "https://predict-mate-backend.fly.dev";
        proxy_pass $backend;
        proxy_set_header Host predict-mate-backend.fly.dev;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_ssl_server_name on;
    }
}
