# Generated by Django 6.0.2 on 2026-04-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', 'Group A'), ('B', 'Group B'), ('C', 'Group C'), ('D', 'Group D'), ('E', 'Group E'), ('F', 'Group F'), ('G', 'Group G'), ('H', 'Group H'), ('I', 'Group I'), ('J', 'Group J'), ('K', 'Group K'), ('L', 'Group L')], max_length=1, unique=True)),
                ('teams', models.ManyToManyField(blank=True, related_name='groups', to='teams.team')),
            ],
            options={
                'verbose_name': 'Match Group',
                'verbose_name_plural': 'Match Groups',
            },
        ),
    ]
