# Generated by Django 6.0.2 on 2026-04-28 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Match Group', 'verbose_name_plural': 'Match Groups'},
        ),
    ]
