# Generated by Django 6.0.2 on 2026-06-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_create_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slot_p1',
            field=models.CharField(blank=True, choices=[('home', 'Home'), ('away', 'Away')], default='', max_length=4),
        ),
        migrations.AddField(
            model_name='group',
            name='slot_p2',
            field=models.CharField(blank=True, choices=[('home', 'Home'), ('away', 'Away')], default='', max_length=4),
        ),
        migrations.AddField(
            model_name='group',
            name='slot_p3',
            field=models.CharField(blank=True, choices=[('home', 'Home'), ('away', 'Away')], default='', max_length=4),
        ),
    ]
