# Generated by Django 6.0.2 on 2026-04-25 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_home_team', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_away_team', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('round', models.CharField(choices=[('GS', 'Group Stage'), ('PO', 'Play-Off'), ('R16', 'Round of 16'), ('QF', 'Quarter Final'), ('SF', 'Semi Final'), ('F', 'Final')], max_length=10)),
                ('leg', models.IntegerField(blank=True, choices=[(1, 'First Leg'), (2, 'Second Leg')], null=True)),
                ('stadium', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('is_finished', models.BooleanField(default=False)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='teams.team')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='groups.group')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='teams.team')),
            ],
            options={
                'verbose_name_plural': 'matches',
                'constraints': [models.UniqueConstraint(fields=('round', 'leg', 'home_team', 'away_team'), name='unique_home_team_per_leg')],
            },
        ),
    ]
