# Generated by Django 6.0.2 on 2026-03-04 21:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(choices=[('GS', 'Group Stage'), ('PO', 'Play-Off'), ('R16', 'Round of 16'), ('QF', 'Quarter Final'), ('SF', 'Semi Final'), ('F', 'Final')], max_length=10)),
                ('score_home_team', models.PositiveSmallIntegerField(default=0)),
                ('score_away_team', models.PositiveSmallIntegerField(default=0)),
                ('leg', models.IntegerField(choices=[(1, '1st Leg'), (2, '2nd Leg')], default=1)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='teams.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='teams.team')),
            ],
            options={
                'verbose_name_plural': 'matches',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(125)])),
                ('is_penalty', models.BooleanField(default=False)),
                ('is_own_goal', models.BooleanField(default=False, editable=False)),
                ('assist_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assists', to='players.player')),
                ('goalscorer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='players.player')),
                ('team_scored', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='teams.team')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='matches.match')),
            ],
            options={
                'ordering': ['minute'],
            },
        ),
    ]
