# Generated by Django 6.0.2 on 2026-03-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('round', 'leg', 'home_team'), name='unique_home_team_per_leg'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('round', 'leg', 'away_team'), name='unique_away_team_per_leg'),
        ),
    ]
