# Generated by Django 6.0.2 on 2026-05-23 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_away_placeholder_match_home_placeholder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='next_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeder_matches', to='matches.match'),
        ),
        migrations.AddField(
            model_name='match',
            name='next_match_slot',
            field=models.CharField(blank=True, choices=[('home', 'Home'), ('away', 'Away')], default='', max_length=4),
        ),
    ]
