# Generated by Django 6.0.2 on 2026-05-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_match_next_match_match_next_match_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='round',
            field=models.CharField(choices=[('GS', 'Group Stage'), ('PO', 'Play-Off'), ('R32', 'Round of 32'), ('R16', 'Round of 16'), ('QF', 'Quarter Final'), ('SF', 'Semi Final'), ('F', 'Final')], max_length=10),
        ),
    ]
