# Generated by Django 6.0.2 on 2026-03-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_remove_match_unique_home_team_per_leg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='leg',
            field=models.IntegerField(blank=True, choices=[(1, '1st Leg'), (2, '2nd Leg')], null=True),
        ),
    ]
