# Generated by Django 6.0.2 on 2026-04-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_match_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='group',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_away_team',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_home_team',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
