# Generated by Django 6.0.2 on 2026-06-03 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(125)])),
                ('is_penalty', models.BooleanField(default=False)),
                ('is_own_goal', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'ordering': ['minute'],
            },
        ),
    ]
