# Generated by Django 6.0.2 on 2026-04-25 20:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('players', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(125)])),
                ('is_penalty', models.BooleanField(default=False)),
                ('is_own_goal', models.BooleanField(default=False, editable=False)),
                ('assist_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assists', to='players.player')),
                ('goalscorer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='players.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='matches.match')),
                ('team_scored', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='teams.team')),
            ],
            options={
                'ordering': ['minute'],
            },
        ),
    ]
