# Generated by Django 6.0.2 on 2026-06-03 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
        ('matches', '0001_initial'),
        ('players', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='assist_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assists', to='players.player'),
        ),
        migrations.AddField(
            model_name='goal',
            name='goalscorer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='players.player'),
        ),
        migrations.AddField(
            model_name='goal',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='matches.match'),
        ),
        migrations.AddField(
            model_name='goal',
            name='team_scored',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='teams.team'),
        ),
    ]
