# Generated by Django 6.0.2 on 2026-04-29 19:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, choices=[('FR', 'France'), ('GB', 'England'), ('ES', 'Spain'), ('DE', 'Germany'), ('IT', 'Italy'), ('PT', 'Portugal'), ('NO', 'Norway'), ('TR', 'Turkey'), ('NL', 'Netherlands'), ('GR', 'Greece'), ('', 'Other')], max_length=2, verbose_name='Country')),
                ('country_name', models.CharField(blank=True, max_length=50, verbose_name='Country Name')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('FW', 'Forward'), ('MF', 'Midfielder'), ('DF', 'Defender'), ('GK', 'Goalkeeper')], max_length=100)),
                ('jersey_number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='teams.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('team', 'jersey_number'), name='unique_jersey_per_team')],
            },
        ),
    ]
