# Generated by Django 6.0.2 on 2026-04-25 20:17

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, choices=[('FR', 'France'), ('GB', 'England'), ('ES', 'Spain'), ('DE', 'Germany'), ('IT', 'Italy'), ('PT', 'Portugal'), ('NO', 'Norway'), ('TR', 'Turkey'), ('NL', 'Netherlands'), ('GR', 'Greece'), ('', 'Other')], max_length=2, verbose_name='Country')),
                ('country_name', models.CharField(blank=True, max_length=50, verbose_name='Country Name')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_name', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
                ('logo', models.FileField(blank=True, default='', upload_to='logos/')),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_team_name_case_insensitive')],
            },
        ),
    ]
