# Generated by Django 6.0.2 on 2026-04-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
