# Generated by Django 6.0.2 on 2026-04-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
