# Generated by Django 6.0.2 on 2026-04-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.FileField(blank=True, default='', upload_to='logos/'),
        ),
    ]
